image: node:19-alpine

#variables:
#  ANSIBLE_CONFIG: "./ansible/ansible.cfg"
#  ANSIBLE_FORCE_COLOR: "true"

before_script:
  - echo "Install requirements..."
  - apk update
  - apk add --no-cache git
  # Java
  - apk add --no-cache openjdk11
  - apk add --no-cache graphviz
  - apk add --no-cache fontconfig ttf-dejavu
  # Jekyll
  - apk add --no-cache jekyll
  # Version checks
  - echo "Version check:"
  - node --version
  - npm --version
  - java -version
  - jekyll --version
  # FHIR
  - npm install -g fsh-sushi
  # FHIR IG Publisher
  - mkdir -p ./input-cache
  - wget -O "./input-cache/publisher.jar" "https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - java -jar input-cache/publisher.jar -ig ig.ini
  cache:
    paths:
      - ./input-cache
      - ./output
  artifacts:
    paths:
      - ./output
      - ./fsh-generated

pages:
  stage: deploy
  interruptible: true
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mv ./output ./public
  cache:
    paths:
      - ./output
    policy: pull
  artifacts:
    paths:
      - public
